### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by mbonakda**
update cmake command in readme to include ICU_ROOT. fixes FindICU.cmake error.

### CODE REVIEW

**Comment by smassung** [comment]
Thanks for the contribution, but I don't think that path will be applicable for all systems. For example, the path to ICU for me is `/usr/lib/icu` (which is found by the CMakeFile automatically). If you want to add something, you can say something along the lines of:

If the ICU library is unable to be found, you may need to add the flag `-DICU_ROOT=/path/to/icu`

**Comment by mbonakda** [comment]
I was following the convention found in the README.md in the main meta repo: https://github.com/meta-toolkit/meta. I think the command I added matches that one exactly.

EDIT: Ah, I see. Maybe this is only for OS X?

**Comment by smassung** [comment]
Oh, that's for OS X. You should create an OS X section or mention that it's only for OS X (as an alternative command). Thanks!

Edit -- yes, you're correct.

**Comment by smassung** [comment]
Thanks. Just one last small nitpick -- I would change "Ubuntu" to just "Linux" for now, since the directions should be generic enough for most linux distros. Besides, there is a specific Ubuntu section in the MeTA readme that installs necessary libraries, and it's probably not worth adding those instructions into `search-app` (unless you want to for some reason).

**Comment by mbonakda** [comment]
Sure thing -- done! I wrote Ubuntu to match the MeTA readme, but I thought Linux would be better too.

**Comment by smassung** [comment]
Cool, thanks for the contribution!

(There are a couple different linux setups in the MeTA readme btw)

**Pull request merged**
